id: P005434
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22238
  title: ང་ནི་བོད་ཡིན།
  author: ''
  volumes:
    12b612383c1448bbb33042b5204ed5de:
      image_group_id: I1KG22307
      title: ''
      volume_number: 1
      total_pages: 176
